"""AI provider/model/agent table definitions."""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    JSON,
    MetaData,
    String,
    Table,
    Text,
)

metadata = MetaData()

ai_providers_table = Table(
    "ai_providers",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("provider_key", String(64), nullable=False),
    Column("display_name", String(160), nullable=False),
    Column("provider_type", String(80), nullable=False),
    Column("default_base_url", String(512), nullable=True),
    Column("documentation_url", String(512), nullable=True),
    Column("status", String(32), nullable=False),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

ai_provider_accounts_table = Table(
    "ai_provider_accounts",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("ai_provider_id", String(36), nullable=False),
    Column("display_name", String(160), nullable=False),
    Column("base_url", String(512), nullable=True),
    Column("auth_secret_ref", String(512), nullable=True),
    Column("plan_type", String(80), nullable=False),
    Column("enabled", Boolean, nullable=False),
    Column("priority", Integer, nullable=False),
    Column("request_timeout_seconds", Float, nullable=False),
    Column("policy_warning_required", Boolean, nullable=False),
    Column("policy_warning_acknowledged_at", DateTime(timezone=True), nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("notes", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

ai_models_table = Table(
    "ai_models",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("ai_provider_id", String(36), nullable=False),
    Column("provider_model_name", String(160), nullable=False),
    Column("normalized_model_name", String(160), nullable=False),
    Column("display_name", String(160), nullable=False),
    Column("model_type", String(64), nullable=False),
    Column("context_window_tokens", Integer, nullable=True),
    Column("max_output_tokens", Integer, nullable=True),
    Column("supports_structured_output", Boolean, nullable=False),
    Column("supports_json_mode", Boolean, nullable=False),
    Column("supports_thinking", Boolean, nullable=False),
    Column("supports_tools", Boolean, nullable=False),
    Column("supports_streaming", Boolean, nullable=False),
    Column("supports_image_input", Boolean, nullable=False),
    Column("supports_document_input", Boolean, nullable=False),
    Column("supports_audio_input", Boolean, nullable=False),
    Column("supports_video_input", Boolean, nullable=False),
    Column("default_temperature", Float, nullable=True),
    Column("status", String(32), nullable=False),
    Column("source_url", String(512), nullable=True),
    Column("verified_at", DateTime(timezone=True), nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

ai_model_limits_table = Table(
    "ai_model_limits",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("ai_provider_id", String(36), nullable=False),
    Column("ai_model_id", String(36), nullable=False),
    Column("limit_scope", String(64), nullable=False),
    Column("raw_limit", Integer, nullable=False),
    Column("utilization_ratio", Float, nullable=False),
    Column("effective_limit", Integer, nullable=False),
    Column("window_seconds", Integer, nullable=True),
    Column("source", String(80), nullable=False),
    Column("quota_multiplier_json", JSON, nullable=True),
    Column("source_url", String(512), nullable=True),
    Column("verified_at", DateTime(timezone=True), nullable=True),
    Column("notes", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

ai_agents_table = Table(
    "ai_agents",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("agent_key", String(120), nullable=False),
    Column("display_name", String(160), nullable=False),
    Column("task_type", String(80), nullable=False),
    Column("input_schema_json", JSON, nullable=True),
    Column("output_schema_json", JSON, nullable=True),
    Column("default_strategy", String(80), nullable=False),
    Column("enabled", Boolean, nullable=False),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

ai_agent_routes_table = Table(
    "ai_agent_routes",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("ai_agent_id", String(36), nullable=False),
    Column("ai_provider_account_id", String(36), nullable=False),
    Column("ai_model_id", String(36), nullable=False),
    Column("route_role", String(64), nullable=False),
    Column("priority", Integer, nullable=False),
    Column("weight", Float, nullable=False),
    Column("enabled", Boolean, nullable=False),
    Column("max_input_tokens", Integer, nullable=True),
    Column("max_output_tokens", Integer, nullable=True),
    Column("temperature", Float, nullable=True),
    Column("thinking_enabled", Boolean, nullable=False),
    Column("structured_output_required", Boolean, nullable=False),
    Column("fallback_on_error", Boolean, nullable=False),
    Column("fallback_on_rate_limit", Boolean, nullable=False),
    Column("fallback_on_invalid_output", Boolean, nullable=False),
    Column("route_conditions_json", JSON, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

ai_runs_table = Table(
    "ai_runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("ai_agent_id", String(36), nullable=False),
    Column("agent_key", String(120), nullable=False),
    Column("task_type", String(80), nullable=False),
    Column("scheduler_job_id", String(36), nullable=True),
    Column("source_id", String(36), nullable=True),
    Column("source_message_id", String(36), nullable=True),
    Column("artifact_id", String(36), nullable=True),
    Column("lead_event_id", String(36), nullable=True),
    Column("lead_cluster_id", String(36), nullable=True),
    Column("catalog_version_id", String(36), nullable=True),
    Column("input_hash", String(64), nullable=True),
    Column("settings_hash", String(64), nullable=True),
    Column("status", String(32), nullable=False),
    Column("strategy", String(80), nullable=True),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("error", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

ai_run_outputs_table = Table(
    "ai_run_outputs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("ai_run_id", String(36), nullable=False),
    Column("ai_agent_route_id", String(36), nullable=True),
    Column("ai_provider_account_id", String(36), nullable=True),
    Column("ai_model_id", String(36), nullable=True),
    Column("provider", String(64), nullable=False),
    Column("model", String(160), nullable=False),
    Column("model_type", String(64), nullable=False),
    Column("route_role", String(64), nullable=False),
    Column("request_started_at", DateTime(timezone=True), nullable=True),
    Column("request_finished_at", DateTime(timezone=True), nullable=True),
    Column("status", String(32), nullable=False),
    Column("prompt_tokens", Integer, nullable=True),
    Column("completion_tokens", Integer, nullable=True),
    Column("total_tokens", Integer, nullable=True),
    Column("cached_tokens", Integer, nullable=True),
    Column("estimated_tokens", Integer, nullable=True),
    Column("temperature", Float, nullable=True),
    Column("max_tokens", Integer, nullable=True),
    Column("thinking_enabled", Boolean, nullable=False),
    Column("raw_request_json", JSON, nullable=True),
    Column("raw_response_json", JSON, nullable=True),
    Column("parsed_output_json", JSON, nullable=True),
    Column("schema_validation_json", JSON, nullable=True),
    Column("error", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

ai_model_concurrency_leases_table = Table(
    "ai_model_concurrency_leases",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("provider", String(64), nullable=False),
    Column("ai_model_id", String(36), nullable=True),
    Column("model", String(160), nullable=False),
    Column("normalized_model", String(160), nullable=False),
    Column("worker_name", String(160), nullable=False),
    Column("ai_run_id", String(36), nullable=True),
    Column("ai_run_output_id", String(36), nullable=True),
    Column("raw_limit", Integer, nullable=True),
    Column("utilization_ratio", Float, nullable=True),
    Column("effective_limit", Integer, nullable=True),
    Column("acquired_at", DateTime(timezone=True), nullable=False),
    Column("lease_expires_at", DateTime(timezone=True), nullable=False),
    Column("metadata_json", JSON, nullable=True),
)
