"""Catalog source-of-truth table definitions."""

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    Integer,
    JSON,
    MetaData,
    String,
    Table,
    Text,
)

metadata = MetaData()

sources_table = Table(
    "sources",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("source_type", String(64), nullable=False),
    Column("origin", String(255), nullable=False),
    Column("external_id", String(512), nullable=False),
    Column("url", String(1024), nullable=True),
    Column("title", String(512), nullable=True),
    Column("author", String(255), nullable=True),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("fetched_at", DateTime(timezone=True), nullable=True),
    Column("raw_text", Text, nullable=True),
    Column("normalized_text", Text, nullable=True),
    Column("content_hash", String(64), nullable=False),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

artifacts_table = Table(
    "artifacts",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("source_id", String(36), nullable=False),
    Column("artifact_type", String(64), nullable=False),
    Column("file_name", String(512), nullable=True),
    Column("mime_type", String(255), nullable=True),
    Column("file_size", Integer, nullable=True),
    Column("sha256", String(64), nullable=True),
    Column("local_path", String(1024), nullable=True),
    Column("download_status", String(32), nullable=False),
    Column("skip_reason", String(64), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

parsed_chunks_table = Table(
    "parsed_chunks",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("source_id", String(36), nullable=False),
    Column("artifact_id", String(36), nullable=True),
    Column("chunk_index", Integer, nullable=False),
    Column("text", Text, nullable=False),
    Column("token_estimate", Integer, nullable=False),
    Column("parser_name", String(160), nullable=False),
    Column("parser_version", String(80), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

extraction_runs_table = Table(
    "extraction_runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("run_type", String(64), nullable=False),
    Column("model", String(160), nullable=True),
    Column("prompt_version", String(80), nullable=True),
    Column("catalog_version_id", String(36), nullable=True),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("status", String(32), nullable=False),
    Column("error", Text, nullable=True),
    Column("stats_json", JSON, nullable=True),
    Column("source_scope_json", JSON, nullable=True),
    Column("extractor_version", String(80), nullable=False),
    Column("candidate_count", Integer, nullable=False),
    Column("fact_count", Integer, nullable=False),
    Column("created_catalog_entity_count", Integer, nullable=False),
    Column("token_usage_json", JSON, nullable=True),
)

catalog_versions_table = Table(
    "catalog_versions",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("version", Integer, nullable=False),
    Column("catalog_hash", String(64), nullable=False),
    Column("candidate_hash", String(64), nullable=True),
    Column("item_count", Integer, nullable=False),
    Column("term_count", Integer, nullable=False),
    Column("offer_count", Integer, nullable=False),
    Column("included_statuses_json", JSON, nullable=False),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("notes", Text, nullable=True),
)

extracted_facts_table = Table(
    "extracted_facts",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("extraction_run_id", String(36), nullable=False),
    Column("source_id", String(36), nullable=True),
    Column("chunk_id", String(36), nullable=True),
    Column("fact_type", String(64), nullable=False),
    Column("canonical_name", String(512), nullable=False),
    Column("value_json", JSON, nullable=False),
    Column("confidence", Float, nullable=False),
    Column("status", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

catalog_candidates_table = Table(
    "catalog_candidates",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("candidate_type", String(64), nullable=False),
    Column("proposed_action", String(32), nullable=False),
    Column("canonical_name", String(512), nullable=False),
    Column("normalized_value_json", JSON, nullable=False),
    Column("source_count", Integer, nullable=False),
    Column("evidence_count", Integer, nullable=False),
    Column("confidence", Float, nullable=False),
    Column("status", String(32), nullable=False),
    Column("target_entity_type", String(64), nullable=True),
    Column("target_entity_id", String(36), nullable=True),
    Column("merge_target_candidate_id", String(36), nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

catalog_candidate_facts_table = Table(
    "catalog_candidate_facts",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("catalog_candidate_id", String(36), nullable=False),
    Column("extracted_fact_id", String(36), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

catalog_categories_table = Table(
    "catalog_categories",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("parent_id", String(36), nullable=True),
    Column("slug", String(160), nullable=False),
    Column("name", String(255), nullable=False),
    Column("description", Text, nullable=True),
    Column("status", String(32), nullable=False),
    Column("sort_order", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

catalog_items_table = Table(
    "catalog_items",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("category_id", String(36), nullable=True),
    Column("item_type", String(64), nullable=False),
    Column("name", String(512), nullable=False),
    Column("canonical_name", String(512), nullable=False),
    Column("description", Text, nullable=True),
    Column("status", String(32), nullable=False),
    Column("confidence", Float, nullable=True),
    Column("first_seen_source_id", String(36), nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=True),
    Column("last_seen_at", DateTime(timezone=True), nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

catalog_terms_table = Table(
    "catalog_terms",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("item_id", String(36), nullable=True),
    Column("category_id", String(36), nullable=True),
    Column("term", String(512), nullable=False),
    Column("normalized_term", String(512), nullable=False),
    Column("term_type", String(64), nullable=False),
    Column("language", String(16), nullable=False),
    Column("status", String(32), nullable=False),
    Column("weight", Float, nullable=False),
    Column("created_by", String(160), nullable=False),
    Column("first_seen_source_id", String(36), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

catalog_attributes_table = Table(
    "catalog_attributes",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("item_id", String(36), nullable=False),
    Column("attribute_name", String(255), nullable=False),
    Column("attribute_value", Text, nullable=False),
    Column("value_type", String(32), nullable=False),
    Column("unit", String(64), nullable=True),
    Column("status", String(32), nullable=False),
    Column("valid_from", DateTime(timezone=True), nullable=True),
    Column("valid_to", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

catalog_offers_table = Table(
    "catalog_offers",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("item_id", String(36), nullable=True),
    Column("category_id", String(36), nullable=True),
    Column("offer_type", String(64), nullable=False),
    Column("title", String(512), nullable=False),
    Column("description", Text, nullable=True),
    Column("price_amount", Float, nullable=True),
    Column("currency", String(16), nullable=True),
    Column("price_text", String(255), nullable=True),
    Column("terms_json", JSON, nullable=True),
    Column("status", String(32), nullable=False),
    Column("valid_from", DateTime(timezone=True), nullable=True),
    Column("valid_to", DateTime(timezone=True), nullable=True),
    Column("ttl_days", Integer, nullable=True),
    Column("ttl_source", String(32), nullable=False),
    Column("first_seen_source_id", String(36), nullable=True),
    Column("last_seen_source_id", String(36), nullable=True),
    Column("last_seen_at", DateTime(timezone=True), nullable=True),
    Column("expired_at", DateTime(timezone=True), nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

catalog_relations_table = Table(
    "catalog_relations",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("from_item_id", String(36), nullable=False),
    Column("to_item_id", String(36), nullable=False),
    Column("relation_type", String(64), nullable=False),
    Column("status", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

catalog_evidence_table = Table(
    "catalog_evidence",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("entity_type", String(64), nullable=False),
    Column("entity_id", String(36), nullable=False),
    Column("source_id", String(36), nullable=True),
    Column("artifact_id", String(36), nullable=True),
    Column("chunk_id", String(36), nullable=True),
    Column("quote", Text, nullable=True),
    Column("page_number", Integer, nullable=True),
    Column("location_json", JSON, nullable=True),
    Column("extractor_version", String(80), nullable=True),
    Column("evidence_type", String(64), nullable=False),
    Column("confidence", Float, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

manual_inputs_table = Table(
    "manual_inputs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("input_type", String(64), nullable=False),
    Column("submission_channel", String(32), nullable=False),
    Column("text", Text, nullable=True),
    Column("url", String(1024), nullable=True),
    Column("chat_ref", String(255), nullable=True),
    Column("message_id", Integer, nullable=True),
    Column("submitted_by", String(160), nullable=False),
    Column("submitted_at", DateTime(timezone=True), nullable=False),
    Column("processing_status", String(32), nullable=False),
    Column("metadata_json", JSON, nullable=True),
)

classifier_examples_table = Table(
    "classifier_examples",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("example_type", String(64), nullable=False),
    Column("polarity", String(32), nullable=False),
    Column("status", String(32), nullable=False),
    Column("source_message_id", String(36), nullable=True),
    Column("raw_source_id", String(36), nullable=True),
    Column("lead_cluster_id", String(36), nullable=True),
    Column("lead_event_id", String(36), nullable=True),
    Column("category_id", String(36), nullable=True),
    Column("catalog_item_id", String(36), nullable=True),
    Column("catalog_term_id", String(36), nullable=True),
    Column("reason_code", String(80), nullable=True),
    Column("example_text", Text, nullable=False),
    Column("context_json", JSON, nullable=True),
    Column("weight", Float, nullable=False),
    Column("created_from", String(64), nullable=False),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

classifier_versions_table = Table(
    "classifier_versions",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("version", Integer, nullable=False),
    Column("catalog_version_id", String(36), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("created_by", String(160), nullable=False),
    Column("included_statuses_json", JSON, nullable=False),
    Column("catalog_hash", String(64), nullable=False),
    Column("example_hash", String(64), nullable=False),
    Column("prompt_hash", String(64), nullable=False),
    Column("keyword_index_hash", String(64), nullable=False),
    Column("settings_hash", String(64), nullable=False),
    Column("model", String(160), nullable=True),
    Column("model_config_hash", String(64), nullable=True),
    Column("notes", Text, nullable=True),
)

classifier_snapshot_entries_table = Table(
    "classifier_snapshot_entries",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("classifier_version_id", String(36), nullable=False),
    Column("entry_type", String(64), nullable=False),
    Column("entity_type", String(64), nullable=True),
    Column("entity_id", String(36), nullable=True),
    Column("status_at_build", String(32), nullable=True),
    Column("weight", Float, nullable=True),
    Column("text_value", Text, nullable=True),
    Column("normalized_value", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("content_hash", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

classifier_version_artifacts_table = Table(
    "classifier_version_artifacts",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("classifier_version_id", String(36), nullable=False),
    Column("artifact_type", String(64), nullable=False),
    Column("content_text", Text, nullable=True),
    Column("content_json", JSON, nullable=True),
    Column("content_hash", String(64), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)
