"""CRM memory table definitions."""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    JSON,
    MetaData,
    String,
    Table,
    Text,
)

metadata = MetaData()

clients_table = Table(
    "clients",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_type", String(64), nullable=False),
    Column("display_name", String(255), nullable=False),
    Column("status", String(32), nullable=False),
    Column("source_type", String(32), nullable=False),
    Column("source_id", String(36), nullable=True),
    Column("owner_user_id", String(36), nullable=True),
    Column("assignee_user_id", String(36), nullable=True),
    Column("notes", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

contacts_table = Table(
    "contacts",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("contact_name", String(255), nullable=True),
    Column("telegram_user_id", String(80), nullable=True),
    Column("telegram_username", String(160), nullable=True),
    Column("phone", String(80), nullable=True),
    Column("email", String(255), nullable=True),
    Column("whatsapp", String(80), nullable=True),
    Column("preferred_channel", String(32), nullable=False),
    Column("source_type", String(32), nullable=False),
    Column("source_id", String(36), nullable=True),
    Column("is_primary", Boolean, nullable=False),
    Column("notes", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

client_objects_table = Table(
    "client_objects",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("object_type", String(64), nullable=False),
    Column("name", String(255), nullable=False),
    Column("location_text", Text, nullable=True),
    Column("project_stage", String(32), nullable=False),
    Column("notes", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

client_interests_table = Table(
    "client_interests",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("client_object_id", String(36), nullable=True),
    Column("category_id", String(36), nullable=True),
    Column("catalog_item_id", String(36), nullable=True),
    Column("catalog_term_id", String(36), nullable=True),
    Column("interest_text", Text, nullable=False),
    Column("interest_status", String(32), nullable=False),
    Column("source_type", String(32), nullable=False),
    Column("source_id", String(36), nullable=True),
    Column("last_seen_at", DateTime(timezone=True), nullable=True),
    Column("next_check_at", DateTime(timezone=True), nullable=True),
    Column("notes", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

client_assets_table = Table(
    "client_assets",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("client_object_id", String(36), nullable=True),
    Column("category_id", String(36), nullable=True),
    Column("catalog_item_id", String(36), nullable=True),
    Column("asset_name", String(255), nullable=False),
    Column("asset_status", String(32), nullable=False),
    Column("installed_at", DateTime(timezone=True), nullable=True),
    Column("warranty_until", DateTime(timezone=True), nullable=True),
    Column("service_due_at", DateTime(timezone=True), nullable=True),
    Column("source_type", String(32), nullable=False),
    Column("source_id", String(36), nullable=True),
    Column("notes", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

opportunities_table = Table(
    "opportunities",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("client_object_id", String(36), nullable=True),
    Column("source_lead_cluster_id", String(36), nullable=True),
    Column("source_lead_event_id", String(36), nullable=True),
    Column("primary_category_id", String(36), nullable=True),
    Column("title", String(255), nullable=False),
    Column("status", String(32), nullable=False),
    Column("lost_reason", String(64), nullable=True),
    Column("estimated_value", Float, nullable=True),
    Column("currency", String(16), nullable=True),
    Column("owner_user_id", String(36), nullable=True),
    Column("assignee_user_id", String(36), nullable=True),
    Column("next_step", String(255), nullable=True),
    Column("next_step_at", DateTime(timezone=True), nullable=True),
    Column("notes", Text, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("closed_at", DateTime(timezone=True), nullable=True),
)

support_cases_table = Table(
    "support_cases",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("client_object_id", String(36), nullable=True),
    Column("client_asset_id", String(36), nullable=True),
    Column("source_lead_cluster_id", String(36), nullable=True),
    Column("source_lead_event_id", String(36), nullable=True),
    Column("title", String(255), nullable=False),
    Column("status", String(32), nullable=False),
    Column("priority", String(32), nullable=False),
    Column("issue_text", Text, nullable=True),
    Column("resolution_text", Text, nullable=True),
    Column("owner_user_id", String(36), nullable=True),
    Column("assignee_user_id", String(36), nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("closed_at", DateTime(timezone=True), nullable=True),
)

contact_reasons_table = Table(
    "contact_reasons",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("contact_id", String(36), nullable=True),
    Column("client_object_id", String(36), nullable=True),
    Column("client_interest_id", String(36), nullable=True),
    Column("client_asset_id", String(36), nullable=True),
    Column("catalog_item_id", String(36), nullable=True),
    Column("catalog_offer_id", String(36), nullable=True),
    Column("catalog_attribute_id", String(36), nullable=True),
    Column("source_id", String(36), nullable=True),
    Column("source_lead_cluster_id", String(36), nullable=True),
    Column("source_lead_event_id", String(36), nullable=True),
    Column("reason_type", String(64), nullable=False),
    Column("title", String(255), nullable=False),
    Column("reason_text", Text, nullable=False),
    Column("priority", String(32), nullable=False),
    Column("status", String(32), nullable=False),
    Column("due_at", DateTime(timezone=True), nullable=True),
    Column("snoozed_until", DateTime(timezone=True), nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

touchpoints_table = Table(
    "touchpoints",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("client_id", String(36), nullable=False),
    Column("contact_id", String(36), nullable=True),
    Column("opportunity_id", String(36), nullable=True),
    Column("support_case_id", String(36), nullable=True),
    Column("contact_reason_id", String(36), nullable=True),
    Column("lead_cluster_id", String(36), nullable=True),
    Column("lead_event_id", String(36), nullable=True),
    Column("channel", String(32), nullable=False),
    Column("direction", String(32), nullable=False),
    Column("summary", Text, nullable=False),
    Column("outcome", String(255), nullable=True),
    Column("next_step", String(255), nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)
