"""Interest context draft knowledge tables."""

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, JSON, MetaData, String, Table, Text

metadata = MetaData()

interest_context_draft_runs_table = Table(
    "interest_context_draft_runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("context_id", String(36), nullable=False),
    Column("status", String(32), nullable=False),
    Column("algorithm_version", String(80), nullable=False),
    Column("input_summary_json", JSON, nullable=True),
    Column("output_summary_json", JSON, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_context_draft_items_table = Table(
    "interest_context_draft_items",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("draft_run_id", String(36), nullable=False),
    Column("context_id", String(36), nullable=False),
    Column("item_type", String(64), nullable=False),
    Column("title", String(300), nullable=False),
    Column("normalized_key", String(300), nullable=False),
    Column("description", Text, nullable=True),
    Column("score", Float, nullable=False),
    Column("confidence", String(32), nullable=False),
    Column("status", String(32), nullable=False),
    Column("evidence_count", Integer, nullable=False),
    Column("source_message_count", Integer, nullable=False),
    Column("metadata_json", JSON, nullable=True),
    Column("evidence_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_core_candidate_reviews_table = Table(
    "interest_core_candidate_reviews",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("context_id", String(36), nullable=False),
    Column("enhancement_job_id", String(36), nullable=False),
    Column("draft_run_id", String(36), nullable=True),
    Column("source_candidate_id", String(80), nullable=True),
    Column("recommendation_type", String(32), nullable=False),
    Column("canonical_name", String(300), nullable=True),
    Column("category", String(160), nullable=True),
    Column("decision", String(32), nullable=False),
    Column("merge_into_candidate_id", String(80), nullable=True),
    Column("confidence", String(32), nullable=False),
    Column("description", Text, nullable=True),
    Column("synonyms_json", JSON, nullable=True),
    Column("lead_signals_json", JSON, nullable=True),
    Column("noise_patterns_json", JSON, nullable=True),
    Column("evidence_refs_json", JSON, nullable=True),
    Column("rationale", Text, nullable=True),
    Column("status", String(32), nullable=False),
    Column("review_note", Text, nullable=True),
    Column("reviewed_by", String(160), nullable=True),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("applied_at", DateTime(timezone=True), nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_core_items_table = Table(
    "interest_core_items",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("context_id", String(36), nullable=False),
    Column("source_review_id", String(36), nullable=True),
    Column("source_candidate_id", String(80), nullable=True),
    Column("item_type", String(64), nullable=False),
    Column("canonical_name", String(300), nullable=False),
    Column("category", String(160), nullable=True),
    Column("description", Text, nullable=True),
    Column("confidence", String(32), nullable=False),
    Column("status", String(32), nullable=False),
    Column("synonyms_json", JSON, nullable=True),
    Column("lead_signals_json", JSON, nullable=True),
    Column("noise_patterns_json", JSON, nullable=True),
    Column("evidence_refs_json", JSON, nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_core_analysis_runs_table = Table(
    "interest_core_analysis_runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("context_id", String(36), nullable=False),
    Column("monitored_source_id", String(36), nullable=False),
    Column("raw_export_run_id", String(36), nullable=False),
    Column("status", String(32), nullable=False),
    Column("source_title", String(255), nullable=True),
    Column("message_count", Integer, nullable=False),
    Column("core_item_count", Integer, nullable=False),
    Column("matched_message_count", Integer, nullable=False),
    Column("match_count", Integer, nullable=False),
    Column("summary_json", JSON, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_core_analysis_matches_table = Table(
    "interest_core_analysis_matches",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("run_id", String(36), nullable=False),
    Column("context_id", String(36), nullable=False),
    Column("source_message_id", String(36), nullable=False),
    Column("interest_core_item_id", String(36), nullable=False),
    Column("telegram_message_id", Integer, nullable=False),
    Column("message_date", DateTime(timezone=True), nullable=False),
    Column("sender_id", String(80), nullable=True),
    Column("message_text", Text, nullable=True),
    Column("canonical_name", String(300), nullable=True),
    Column("category", String(160), nullable=True),
    Column("matched_text", String(500), nullable=True),
    Column("match_kind", String(64), nullable=False),
    Column("score", Float, nullable=False),
    Column("evidence_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

interest_intent_layers_table = Table(
    "interest_intent_layers",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("context_id", String(36), nullable=False),
    Column("name", String(200), nullable=False),
    Column("description", Text, nullable=True),
    Column("status", String(32), nullable=False),
    Column("include_patterns_json", JSON, nullable=True),
    Column("context_patterns_json", JSON, nullable=True),
    Column("exclude_patterns_json", JSON, nullable=True),
    Column("include_categories_json", JSON, nullable=True),
    Column("exclude_categories_json", JSON, nullable=True),
    Column("include_core_names_json", JSON, nullable=True),
    Column("exclude_core_names_json", JSON, nullable=True),
    Column("require_include_match", Boolean, nullable=False),
    Column("require_context_match", Boolean, nullable=False),
    Column("min_score", Float, nullable=False),
    Column("max_results", Integer, nullable=False),
    Column("broad_score_weight", Float, nullable=False),
    Column("intent_hit_weight", Float, nullable=False),
    Column("metadata_json", JSON, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_intent_analysis_runs_table = Table(
    "interest_intent_analysis_runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("context_id", String(36), nullable=False),
    Column("intent_layer_id", String(36), nullable=False),
    Column("broad_analysis_run_id", String(36), nullable=False),
    Column("status", String(32), nullable=False),
    Column("source_title", String(255), nullable=True),
    Column("source_message_count", Integer, nullable=False),
    Column("broad_match_count", Integer, nullable=False),
    Column("matched_message_count", Integer, nullable=False),
    Column("match_count", Integer, nullable=False),
    Column("summary_json", JSON, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_intent_analysis_matches_table = Table(
    "interest_intent_analysis_matches",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("run_id", String(36), nullable=False),
    Column("context_id", String(36), nullable=False),
    Column("intent_layer_id", String(36), nullable=False),
    Column("source_message_id", String(36), nullable=False),
    Column("interest_core_match_id", String(36), nullable=False),
    Column("interest_core_item_id", String(36), nullable=False),
    Column("telegram_message_id", Integer, nullable=False),
    Column("message_date", DateTime(timezone=True), nullable=False),
    Column("sender_id", String(80), nullable=True),
    Column("message_text", Text, nullable=True),
    Column("canonical_name", String(300), nullable=True),
    Column("category", String(160), nullable=True),
    Column("matched_text", String(500), nullable=True),
    Column("match_kind", String(64), nullable=False),
    Column("score", Float, nullable=False),
    Column("broad_score", Float, nullable=False),
    Column("evidence_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

interest_intent_validation_runs_table = Table(
    "interest_intent_validation_runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("context_id", String(36), nullable=False),
    Column("source_intent_run_id", String(36), nullable=False),
    Column("source_intent_layer_id", String(36), nullable=False),
    Column("status", String(32), nullable=False),
    Column("provider", String(80), nullable=True),
    Column("model", String(160), nullable=True),
    Column("model_profile", String(160), nullable=True),
    Column("ai_provider_account_id", String(36), nullable=True),
    Column("ai_model_id", String(36), nullable=True),
    Column("ai_model_profile_id", String(36), nullable=True),
    Column("ai_agent_route_id", String(36), nullable=True),
    Column("prompt_version", String(80), nullable=False),
    Column("prompt_text", Text, nullable=True),
    Column("request_json", JSON, nullable=True),
    Column("response_json", JSON, nullable=True),
    Column("parsed_response_json", JSON, nullable=True),
    Column("summary_json", JSON, nullable=True),
    Column("recommendation_count", Integer, nullable=False),
    Column("created_layer_id", String(36), nullable=True),
    Column("error", Text, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

interest_intent_validation_recommendations_table = Table(
    "interest_intent_validation_recommendations",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("validation_run_id", String(36), nullable=False),
    Column("context_id", String(36), nullable=False),
    Column("source_intent_run_id", String(36), nullable=False),
    Column("recommendation_type", String(80), nullable=False),
    Column("title", String(300), nullable=False),
    Column("rationale", Text, nullable=True),
    Column("confidence", String(32), nullable=False),
    Column("proposed_changes_json", JSON, nullable=True),
    Column("impact_preview_json", JSON, nullable=True),
    Column("status", String(32), nullable=False),
    Column("review_note", Text, nullable=True),
    Column("reviewed_by", String(160), nullable=True),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("applied_at", DateTime(timezone=True), nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)
