"""Lead inbox table definitions."""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    JSON,
    MetaData,
    String,
    Table,
    Text,
)

metadata = MetaData()

lead_clusters_table = Table(
    "lead_clusters",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("monitored_source_id", String(36), nullable=True),
    Column("chat_id", String(80), nullable=True),
    Column("primary_sender_id", String(80), nullable=True),
    Column("primary_sender_name", String(255), nullable=True),
    Column("primary_lead_event_id", String(36), nullable=True),
    Column("primary_source_message_id", String(36), nullable=True),
    Column("category_id", String(36), nullable=True),
    Column("summary", Text, nullable=True),
    Column("cluster_status", String(32), nullable=False),
    Column("review_status", String(32), nullable=False),
    Column("work_outcome", String(64), nullable=False),
    Column("first_message_at", DateTime(timezone=True), nullable=True),
    Column("last_message_at", DateTime(timezone=True), nullable=True),
    Column("message_count", Integer, nullable=False),
    Column("lead_event_count", Integer, nullable=False),
    Column("confidence_max", Float, nullable=True),
    Column("commercial_value_score_max", Float, nullable=True),
    Column("negative_score_min", Float, nullable=True),
    Column("dedupe_key", String(255), nullable=True),
    Column("merge_strategy", String(32), nullable=False),
    Column("merge_reason", Text, nullable=True),
    Column("last_notified_at", DateTime(timezone=True), nullable=True),
    Column("notify_update_count", Integer, nullable=False),
    Column("snoozed_until", DateTime(timezone=True), nullable=True),
    Column("duplicate_of_cluster_id", String(36), nullable=True),
    Column("primary_task_id", String(36), nullable=True),
    Column("converted_entity_type", String(64), nullable=True),
    Column("converted_entity_id", String(36), nullable=True),
    Column("crm_candidate_count", Integer, nullable=False),
    Column("crm_conversion_action_id", String(36), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

lead_events_table = Table(
    "lead_events",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("source_message_id", String(36), nullable=False),
    Column("monitored_source_id", String(36), nullable=False),
    Column("raw_source_id", String(36), nullable=True),
    Column("chat_id", String(80), nullable=True),
    Column("telegram_message_id", Integer, nullable=False),
    Column("message_url", String(1024), nullable=True),
    Column("sender_id", String(80), nullable=True),
    Column("sender_name", String(255), nullable=True),
    Column("message_text", Text, nullable=True),
    Column("lead_cluster_id", String(36), nullable=True),
    Column("detected_at", DateTime(timezone=True), nullable=False),
    Column("classifier_version_id", String(36), nullable=False),
    Column("decision", String(32), nullable=False),
    Column("detection_mode", String(32), nullable=False),
    Column("confidence", Float, nullable=False),
    Column("commercial_value_score", Float, nullable=True),
    Column("negative_score", Float, nullable=True),
    Column("high_value_signals_json", JSON, nullable=True),
    Column("negative_signals_json", JSON, nullable=True),
    Column("notify_reason", String(255), nullable=True),
    Column("reason", Text, nullable=True),
    Column("event_status", String(32), nullable=False),
    Column("event_review_status", String(32), nullable=False),
    Column("duplicate_of_lead_event_id", String(36), nullable=True),
    Column("is_retro", Boolean, nullable=False),
    Column("original_detected_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

lead_cluster_members_table = Table(
    "lead_cluster_members",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("lead_cluster_id", String(36), nullable=False),
    Column("source_message_id", String(36), nullable=True),
    Column("lead_event_id", String(36), nullable=True),
    Column("member_role", String(32), nullable=False),
    Column("added_by", String(32), nullable=False),
    Column("merge_score", Float, nullable=True),
    Column("merge_reason", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

lead_cluster_actions_table = Table(
    "lead_cluster_actions",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("action_type", String(64), nullable=False),
    Column("from_cluster_id", String(36), nullable=True),
    Column("to_cluster_id", String(36), nullable=True),
    Column("source_message_id", String(36), nullable=True),
    Column("lead_event_id", String(36), nullable=True),
    Column("actor", String(160), nullable=False),
    Column("reason", Text, nullable=True),
    Column("details_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

lead_matches_table = Table(
    "lead_matches",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("lead_event_id", String(36), nullable=False),
    Column("source_message_id", String(36), nullable=False),
    Column("classifier_snapshot_entry_id", String(36), nullable=True),
    Column("catalog_item_id", String(36), nullable=True),
    Column("catalog_term_id", String(36), nullable=True),
    Column("catalog_offer_id", String(36), nullable=True),
    Column("category_id", String(36), nullable=True),
    Column("match_type", String(64), nullable=False),
    Column("matched_text", Text, nullable=True),
    Column("score", Float, nullable=False),
    Column("item_status_at_detection", String(32), nullable=True),
    Column("term_status_at_detection", String(32), nullable=True),
    Column("offer_status_at_detection", String(32), nullable=True),
    Column("matched_weight", Float, nullable=True),
    Column("matched_status_snapshot", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

feedback_events_table = Table(
    "feedback_events",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("target_type", String(64), nullable=False),
    Column("target_id", String(36), nullable=False),
    Column("action", String(80), nullable=False),
    Column("reason_code", String(80), nullable=True),
    Column("feedback_scope", String(64), nullable=False),
    Column("learning_effect", String(80), nullable=False),
    Column("application_status", String(32), nullable=False),
    Column("applied_entity_type", String(64), nullable=True),
    Column("applied_entity_id", String(36), nullable=True),
    Column("applied_at", DateTime(timezone=True), nullable=True),
    Column("comment", Text, nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("metadata_json", JSON, nullable=True),
)

crm_conversion_candidates_table = Table(
    "crm_conversion_candidates",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("lead_cluster_id", String(36), nullable=False),
    Column("lead_event_id", String(36), nullable=True),
    Column("candidate_type", String(64), nullable=False),
    Column("extracted_json", JSON, nullable=False),
    Column("display_summary", Text, nullable=False),
    Column("confidence", Float, nullable=False),
    Column("status", String(32), nullable=False),
    Column("created_by", String(32), nullable=False),
    Column("created_entity_type", String(64), nullable=True),
    Column("created_entity_id", String(36), nullable=True),
    Column("reviewed_by", String(160), nullable=True),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

crm_conversion_actions_table = Table(
    "crm_conversion_actions",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("lead_cluster_id", String(36), nullable=False),
    Column("action_type", String(64), nullable=False),
    Column("used_candidate_ids_json", JSON, nullable=True),
    Column("created_entity_type", String(64), nullable=True),
    Column("created_entity_id", String(36), nullable=True),
    Column("linked_client_id", String(36), nullable=True),
    Column("linked_contact_id", String(36), nullable=True),
    Column("manual_changes_json", JSON, nullable=True),
    Column("next_step", String(255), nullable=True),
    Column("next_step_at", DateTime(timezone=True), nullable=True),
    Column("created_by", String(160), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)
