"""Telegram source ingestion table definitions."""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    JSON,
    MetaData,
    String,
    Table,
    Text,
)

metadata = MetaData()

telegram_bots_table = Table(
    "telegram_bots",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("display_name", String(160), nullable=False),
    Column("telegram_bot_id", String(80), nullable=True),
    Column("telegram_username", String(160), nullable=True),
    Column("token_secret_ref", String(36), nullable=False),
    Column("status", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

telegram_notification_groups_table = Table(
    "telegram_notification_groups",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("telegram_bot_id", String(36), nullable=False),
    Column("chat_id", String(120), nullable=False),
    Column("title", String(255), nullable=True),
    Column("chat_type", String(64), nullable=True),
    Column("message_thread_id", Integer, nullable=True),
    Column("status", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

userbot_accounts_table = Table(
    "userbot_accounts",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("display_name", String(160), nullable=False),
    Column("telegram_user_id", String(64), nullable=True),
    Column("telegram_username", String(160), nullable=True),
    Column("session_name", String(160), nullable=False),
    Column("session_path", String(512), nullable=False),
    Column("status", String(32), nullable=False),
    Column("priority", String(32), nullable=False),
    Column("max_parallel_telegram_jobs", Integer, nullable=False),
    Column("flood_sleep_threshold_seconds", Integer, nullable=False),
    Column("last_connected_at", DateTime(timezone=True), nullable=True),
    Column("last_error", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

monitored_sources_table = Table(
    "monitored_sources",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("source_kind", String(64), nullable=False),
    Column("telegram_id", String(80), nullable=True),
    Column("username", String(160), nullable=True),
    Column("title", String(255), nullable=True),
    Column("invite_link_hash", String(128), nullable=True),
    Column("input_ref", String(512), nullable=False),
    Column("source_purpose", String(32), nullable=False),
    Column("interest_context_id", String(36), nullable=True),
    Column("assigned_userbot_account_id", String(36), nullable=True),
    Column("priority", String(32), nullable=False),
    Column("status", String(64), nullable=False),
    Column("lead_detection_enabled", Boolean, nullable=False),
    Column("catalog_ingestion_enabled", Boolean, nullable=False),
    Column("phase_enabled", Boolean, nullable=False),
    Column("start_mode", String(32), nullable=False),
    Column("start_message_id", Integer, nullable=True),
    Column("start_recent_limit", Integer, nullable=True),
    Column("start_recent_days", Integer, nullable=True),
    Column("historical_backfill_policy", String(32), nullable=False),
    Column("checkpoint_message_id", Integer, nullable=True),
    Column("checkpoint_date", DateTime(timezone=True), nullable=True),
    Column("last_preview_at", DateTime(timezone=True), nullable=True),
    Column("preview_message_count", Integer, nullable=True),
    Column("next_poll_at", DateTime(timezone=True), nullable=True),
    Column("poll_interval_seconds", Integer, nullable=False),
    Column("last_success_at", DateTime(timezone=True), nullable=True),
    Column("last_error_at", DateTime(timezone=True), nullable=True),
    Column("last_error", Text, nullable=True),
    Column("added_by", String(160), nullable=False),
    Column("activated_by", String(160), nullable=True),
    Column("activated_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

source_access_checks_table = Table(
    "source_access_checks",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("monitored_source_id", String(36), nullable=False),
    Column("userbot_account_id", String(36), nullable=True),
    Column("check_type", String(64), nullable=False),
    Column("status", String(64), nullable=False),
    Column("resolved_source_kind", String(64), nullable=True),
    Column("resolved_telegram_id", String(80), nullable=True),
    Column("resolved_title", String(255), nullable=True),
    Column("last_message_id", Integer, nullable=True),
    Column("can_read_messages", Boolean, nullable=False),
    Column("can_read_history", Boolean, nullable=False),
    Column("flood_wait_seconds", Integer, nullable=True),
    Column("error", Text, nullable=True),
    Column("checked_at", DateTime(timezone=True), nullable=False),
)

source_preview_messages_table = Table(
    "source_preview_messages",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("monitored_source_id", String(36), nullable=False),
    Column("access_check_id", String(36), nullable=True),
    Column("telegram_message_id", Integer, nullable=False),
    Column("message_date", DateTime(timezone=True), nullable=False),
    Column("sender_display", String(255), nullable=True),
    Column("text", Text, nullable=True),
    Column("caption", Text, nullable=True),
    Column("has_media", Boolean, nullable=False),
    Column("media_metadata_json", JSON, nullable=True),
    Column("sort_order", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

telegram_raw_export_runs_table = Table(
    "telegram_raw_export_runs",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("monitored_source_id", String(36), nullable=False),
    Column("source_ref", String(512), nullable=False),
    Column("source_kind", String(64), nullable=False),
    Column("telegram_id", String(80), nullable=True),
    Column("username", String(160), nullable=True),
    Column("title", String(255), nullable=True),
    Column("export_format", String(64), nullable=False),
    Column("output_dir", String(1024), nullable=False),
    Column("result_json_path", String(1024), nullable=False),
    Column("messages_jsonl_path", String(1024), nullable=False),
    Column("attachments_jsonl_path", String(1024), nullable=False),
    Column("messages_parquet_path", String(1024), nullable=False),
    Column("attachments_parquet_path", String(1024), nullable=False),
    Column("manifest_path", String(1024), nullable=False),
    Column("message_count", Integer, nullable=False),
    Column("attachment_count", Integer, nullable=False),
    Column("status", String(32), nullable=False),
    Column("error", Text, nullable=True),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("metadata_json", JSON, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

source_messages_table = Table(
    "source_messages",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("monitored_source_id", String(36), nullable=False),
    Column("raw_source_id", String(36), nullable=True),
    Column("telegram_message_id", Integer, nullable=False),
    Column("sender_id", String(80), nullable=True),
    Column("message_date", DateTime(timezone=True), nullable=False),
    Column("text", Text, nullable=True),
    Column("caption", Text, nullable=True),
    Column("normalized_text", Text, nullable=True),
    Column("has_media", Boolean, nullable=False),
    Column("media_metadata_json", JSON, nullable=True),
    Column("reply_to_message_id", Integer, nullable=True),
    Column("thread_id", String(80), nullable=True),
    Column("forward_metadata_json", JSON, nullable=True),
    Column("raw_metadata_json", JSON, nullable=True),
    Column("fetched_at", DateTime(timezone=True), nullable=False),
    Column("classification_status", String(32), nullable=False),
    Column("archive_pointer_id", String(36), nullable=True),
    Column("is_archived_stub", Boolean, nullable=False),
    Column("text_archived", Boolean, nullable=False),
    Column("caption_archived", Boolean, nullable=False),
    Column("metadata_archived", Boolean, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

sender_profiles_table = Table(
    "sender_profiles",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("telegram_user_id", String(80), nullable=True),
    Column("telegram_username", String(160), nullable=True),
    Column("display_name", String(255), nullable=True),
    Column("first_seen_source_message_id", String(36), nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=True),
    Column("last_seen_at", DateTime(timezone=True), nullable=True),
    Column("sender_role", String(64), nullable=False),
    Column("role_confidence", Float, nullable=True),
    Column("role_source", String(64), nullable=True),
    Column("crm_contact_id", String(36), nullable=True),
    Column("crm_client_id", String(36), nullable=True),
    Column("feedback_count", Integer, nullable=False),
    Column("notes", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

message_context_links_table = Table(
    "message_context_links",
    metadata,
    Column("id", String(36), primary_key=True),
    Column("source_message_id", String(36), nullable=False),
    Column("related_source_message_id", String(36), nullable=False),
    Column("relation_type", String(64), nullable=False),
    Column("distance", Integer, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)
